### ISSUE TITLE
Backport to older android versions

### ISSUE THREAD

**Issue by dlazaro66** [balysv/material-ripple#14]
I noticed minSdk is set to 14, so some users like me which are forced to support older versions can't use your library.

As an enhancement, if you do not want to support older android versions, you can add a section in the readme.md explaining that you can use this library using the Jake Wharton's animation backport (http://nineoldandroids.com/) changing the imports from `import android.animation.*;` to: `import com.nineoldandroids.animation.*;` ,
`import android.util.Property`; to   `import com.nineoldandroids.util.Property;` and calling function `shouldDelayChildPressedState()`  only if you're using api greater than 14.

Thank and congrats for the great job!
David.

**Comment by d4rkuzs** [comment]
nineoldandroids is deprecated :( is there any other solution?
