### ISSUE TITLE
Gradle can't find library

### ISSUE THREAD

**Issue by kyleparker** [balysv/material-ripple#24]
I found issue #3 and tried what it suggested, but have been unsuccessful in retrieving the library using Gradle. I even went to http://gradleplease.appspot.com/#material-ripple and it couldn't find the library.

Any other suggestions?

**Comment by balysv** [comment]
It is not available in Maven Central, but Sonatype snapshots only. Add this to your `build.gradle`

```groovy
repositories {
    maven {
        url "https://oss.sonatype.org/content/repositories/snapshots/"
    }
}
```
