### ISSUE TITLE
Autostart ripple effect on a View after being created

### ISSUE THREAD

**Issue by septemberboy7** [balysv/material-ripple#25]
Hi Sir,

I want to start the ripple effect on a view after being created. I use View.performClick() method but it doesn't trigger the ripple effect. Is there anyway to do this?

**Comment by mradzinski** [comment]
`performClick()` or `callOnClick()` does not simulate a touch event, and I'm pretty sure that this library bases it's animations on touch events. So, although the `OnClickListener` get called, you are not going to see any animation happening if you use any of the above methods. You will probably want to user `dispatchTouchEvent()`, there's plenty of documentation online about it.
