### ISSUE TITLE
How to set the ripple effect on actionbar/toolbar icons?

### ISSUE THREAD

**Issue by mkersche17** [balysv/material-ripple#27]
Hi balysv, 
is there a way to set the effect  on all icons of a toolbar? 

great work so far!

**Comment by balysv** [comment]
Hey, 
Icons on Toolbar require `Drawable` to be passed in, the ripple effect is implemented as a `View`.
I'm afraid it's currently not possible without using a custom View in a Toolbar and wrapping each of your icon in `MaterialRippleLayout`
