### ISSUE TITLE
PreferenceFragment?

### ISSUE THREAD

**Issue by easyaspi314** [balysv/material-ripple#29]
I was wondering if there was an easy way to use this with a PreferenceFragment/PreferenceScreen.

**Comment by balysv** [comment]
I can't think of an really easy way to do it. Best you can do is iterate through the preference fragment after inflation and wrap the preference views manually

**Comment by easyaspi314** [comment]
Well the PreferenceFragment does have a getListView() but I do not know if
that will help.

On Feb 9, 2015 4:30 AM, "Balys Valentukevicius" <notifications@github.com>
wrote:
>
> I can't think of an really easy way to do it. Best you can do is iterate
through the preference fragment after inflation and wrap the preference
views manually

**Comment by easyaspi314** [comment]
I looked at the code and I thought that if we could separate the Ripple into a Drawable, we could use it as a selector.

**Comment by balysv** [comment]
Yea, that should work, but that would require completely reworking a large part of the library. I'll leave it as it is for now
