### ISSUE TITLE
get AnimationEnd to perform Custom Action after that?

### ISSUE THREAD

**Issue by csaq7151** [balysv/material-ripple#30]
Is it possible to get the End of the Rippleanimation.
I want to make the RippleAnimation to fill the screen and when it is filled( animation ended) the activity should be closed or anotherone should start.

so an ripplelayout.onAnimationEnd with returntype of boolean or something similar would be great

**Comment by balysv** [comment]
Yes, you can use xml attribute to do that:

```app:rippleDelayClick="true"           // if true, delays calls to OnClickListeners until ripple effect ends```

**Comment by csaq7151** [comment]
i know but because of my customlayout it is not possible to call it in xml

**Comment by balysv** [comment]
If having an `OnClickListener` is not an option, then I'm afraid there is no way. I'll add it as an enhancement feature request

**Comment by csaq7151** [comment]
okay thanks anyway.
