### ISSUE TITLE
LongClick not firing when moving finger.

### ISSUE THREAD

**Issue by RhavoX** [balysv/material-ripple#33]
When the LongClick listener is set to the view on which the MaterialRippleLayout is statically applied the event fires only when you don't move your finger while holding. It is the only place from which it is possible to consume the event. It behaves like this even in the demo application.

**Comment by balysv** [comment]
Are you talking about a `MaterialRippleLayout` in a scrollable layout (`AdapterView`, `ScrollView`)? If so, it is the expected behaviour, since touch events are cancelled if scrolling has been detected.

**Comment by RhavoX** [comment]
This is happening when applied on a LinearLayout or a Button

**Comment by balysv** [comment]
Dug into `GestureDetector` source code that is used to check for long clicks and found that they are cancelled on large move events.

http://grepcode.com/file/repository.grepcode.com/java/ext/com.google.android/android/5.0.2_r1/android/view/GestureDetector.java?av=f#566

```java
if (distance > mTouchSlopSquare) {
    handled = mListener.onScroll(mCurrentDownEvent, ev, scrollX, scrollY);
    mLastFocusX = focusX;
    mLastFocusY = focusY;
    mAlwaysInTapRegion = false;
    mHandler.removeMessages(TAP);
    mHandler.removeMessages(SHOW_PRESS);
    mHandler.removeMessages(LONG_PRESS);
}
```

Basically for it to work the whole long click detection should be rewritten inside `MaterialRippleLayout`. PRs are welcome :)
