### ISSUE TITLE
onItemClick is called after onItemLongClick in RecycleView

### ISSUE THREAD

**Issue by k-tigre** [balysv/material-ripple#35]
Hi,
I tried it in a RecycleView with setting app:rippleInAdapter="false",
When I long click on an item in the list, the listener correctly called but immediately after that touch (MotionEvent.ACTION_UP) the onItemClick method of OnItemClickListener get called! even if returning true in onItemLongClick method!

I've tested it with a normal FrameLayout and it hasn't any problem...

It happend when 
`MaterialRippleLayout.setOnClickListener()` and
`MaterialRippleLayout.setOnLongClickListener()`

```
\<com.balysv.materialripple.MaterialRippleLayout>
     \<View/>
\</com.balysv.materialripple.MaterialRippleLayout>"
```

When
`View.setOnClickListener()` and
`View.setOnLongClickListener()`

```
\<com.balysv.materialripple.MaterialRippleLayout>
     \<View/>
\<com.balysv.materialripple.MaterialRippleLayout>
```

Its work ok.

**Comment by balysv** [comment]
RecyclerView is currently not supported, working on it. see #34 for updates
