### ISSUE TITLE
Child view's onClickListener within MaterialRippleLayout doesn't work

### ISSUE THREAD

**Issue by shahidul2k9** [balysv/material-ripple#55]
Hi,
I have custom list adapter of list view where each row is instantiated within "getView(int position, View convertView, ViewGroup parent)" method. The root view of each row is "MaterialRippleLayout" and it has some child views. There I set some click listener of child views. But "onClick(View v)" method is not being called when child view is clicked.

**Comment by pengbs** [comment]
I meet the same problem as you, I use it in expandListView.

**Comment by chapeladmin** [comment]
looks like with listviews the only click handler that works is setting the listview's setOnItemClickListener.

**Comment by rudsonlive** [comment]
I'm with the same problem. I have an item on my list that you click the item to open a detail screen, but if you click an image that exists in the item, open another screen.

If I use the library I can not use the onClick at a separate view.

Any tips?

Thanks,

**Comment by callmepeanut** [comment]
onClickListener is set on the child, you can see at #59
